# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-29 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_v350_credential_plugins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobevent',
            name='created',
            field=('created', models.DateTimeField(auto_now_add=True)),
        ),
    ]