---

- name: Register temporary docker container
  shell:
    cmd: "docker run -v '{{ postgres_data_dir | realpath }}:/var/lib/postgresql' --name awx_tmp centos:8"

- name: Add Docker container as host
  add_host:
    name: awx_tmp
    ansible_connection: docker
  changed_when: false

- name: Check for existing Postgres data (run from inside the container for access to file)
  delegate_to: awx_tmp
  stat:
    path: /var/lib/postgresql/10/data/PG_VERSION
  register: pg_version_file

- name: Record Postgres version
  delegate_to: awx_tmp
  set_fact:
    old_pg_version: "{{ lookup('file', '/var/lib/postgresql/10/data/PG_VERSION') }}"
  when: pg_version_file.stat.exists

- name: Determine whether to upgrade postgres
  set_fact:
    upgrade_postgres: "{{ old_pg_version is defined and old_pg_version.stdout == '10' | bool }}"
  when: not old_pg_version.skipped | bool

- name: Stop AWX before upgrading postgres
  docker_service:
    project_src: "{{ docker_compose_dir }}"
    stopped: true
  when: upgrade_postgres | bool

- name: Upgrade Postgres
  shell: |
    docker run --rm \
      -v {{ postgres_data_dir | realpath }}:/var/lib/postgresql \
      -e PGUSER={{ pg_username }} -e POSTGRES_INITDB_ARGS="-U {{ pg_username }}" \
      tianon/postgres-upgrade:10-to-12 --username={{ pg_username }}
  when: upgrade_postgres | bool

- name: Copy old pg_hba.conf
  delegate_to: awx_tmp
  copy:
    src: /var/lib/postgresql/10/data/pg_hba.conf
    dest: /var/lib/postgresql/12/data/pg_hba.conf
  when: upgrade_postgres | bool

- name: Remove old data directory
  delegate_to: awx_tmp
  file:
    state: absent
    path: /var/lib/postgresql/10/data
  when: compose_start_containers|bool

- name: Clean up temporary container
  docker:
    name: awx_tmp
    state: absent
    force_kill: yes
    
  
